version: "3"

tasks:
    build:
        desc: Build the app
        cmds:
        - GOFLAGS=-mod=mod go build -o discord-bot-golang main.go 

    run: 
        desc: Run the app
        cmds:
        - GOFLAGS=-mod=mod go run main.go -t 

    bot:
        desc: Execute the bot
        cmds:
        - ./discord-bot-golang -t 